# Generated by Django 2.2 on 2020-02-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cellphone',
            field=models.CharField(max_length=13),
        ),
    ]
