# Generated by Django 2.2 on 2020-03-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('paidCalls', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rt60', models.DecimalField(decimal_places=1, max_digits=4)),
                ('tos', models.DecimalField(decimal_places=1, max_digits=4)),
                ('missingOl', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
