# Generated by Django 2.2 on 2020-03-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0002_driversats'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversats',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
