# Generated by Django 2.2 on 2020-04-16 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200414_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='createted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
