# Generated by Django 2.2 on 2020-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_jobapplication_createted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='phoneNumber',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
