# Generated by Django 2.2 on 2019-12-10 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_incident', models.DateField(blank=True)),
                ('club', models.CharField(blank=True, max_length=120)),
                ('call_num', models.IntegerField(blank=True)),
                ('customer_email', models.CharField(blank=True, max_length=120)),
                ('cust_name', models.CharField(blank=True, max_length=120)),
                ('cust_phone', models.CharField(blank=True, max_length=120)),
                ('vehicle', models.CharField(max_length=120)),
                ('damages', models.TextField(blank=True, max_length=120)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drivers.Driver')),
            ],
        ),
    ]
