# Generated by Django 2.2 on 2019-12-10 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('damages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damage',
            name='closed_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='damage',
            name='cost_to_gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='damage',
            name='damage_2',
            field=models.ImageField(blank=True, upload_to='damages/'),
        ),
        migrations.AddField(
            model_name='damage',
            name='damage_3',
            field=models.ImageField(blank=True, upload_to='damages/'),
        ),
        migrations.AddField(
            model_name='damage',
            name='damage_4',
            field=models.ImageField(blank=True, upload_to='damages/'),
        ),
        migrations.AddField(
            model_name='damage',
            name='damage_5',
            field=models.ImageField(blank=True, upload_to='damages/'),
        ),
        migrations.AddField(
            model_name='damage',
            name='damage_6',
            field=models.ImageField(blank=True, upload_to='damages/'),
        ),
        migrations.AddField(
            model_name='damage',
            name='damage_7',
            field=models.ImageField(blank=True, upload_to='damages/'),
        ),
        migrations.AddField(
            model_name='damage',
            name='damage_8',
            field=models.ImageField(blank=True, upload_to='damages/'),
        ),
        migrations.AddField(
            model_name='damage',
            name='damage_9',
            field=models.ImageField(blank=True, upload_to='damages/'),
        ),
        migrations.AddField(
            model_name='damage',
            name='damage_main',
            field=models.ImageField(blank=True, upload_to='damages/'),
        ),
        migrations.AddField(
            model_name='damage',
            name='damages_est',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='damage',
            name='driver_statement',
            field=models.FileField(blank=True, upload_to='damages/'),
        ),
        migrations.AddField(
            model_name='damage',
            name='estimate',
            field=models.FileField(blank=True, upload_to='damages/'),
        ),
        migrations.AddField(
            model_name='damage',
            name='repaired_at',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='damage',
            name='status',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
