# Generated by Django 2.2 on 2019-12-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damages', '0002_auto_20191209_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='closed_date',
            field=models.DateField(blank=True),
        ),
    ]
