# Generated by Django 2.2 on 2019-12-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damages', '0003_auto_20191212_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('insurance', 'Turned into Insurance'), ('waiting', 'Waiting for Cust '), ('inprocess', 'Repair in Process'), ('denied', 'Denied'), ('closed', 'Closed')], default='Reported', max_length=120),
        ),
    ]
