# Generated by Django 2.2 on 2019-12-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damages', '0004_auto_20191212_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='damage_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='damages',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
