# Generated by Django 2.2 on 2020-01-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damages', '0005_auto_20191212_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
