# Generated by Django 2.2 on 2020-01-22 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yard', models.CharField(default='Auburn', max_length=20)),
                ('item', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(default=0.0)),
                ('details', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(upload_to='garageSale/')),
                ('photo_1', models.ImageField(blank=True, upload_to='garageSale/')),
                ('photo_2', models.ImageField(blank=True, upload_to='garageSale/')),
                ('photo_3', models.ImageField(blank=True, upload_to='garageSale/')),
                ('photo_4', models.ImageField(blank=True, upload_to='garageSale/')),
                ('photo_5', models.ImageField(blank=True, upload_to='garageSale/')),
                ('photo_6', models.ImageField(blank=True, upload_to='garageSale/')),
                ('seller', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sellers.Seller')),
            ],
        ),
    ]
