# Generated by Django 2.2 on 2020-04-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('paidCalls', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rt60', models.DecimalField(decimal_places=1, max_digits=4)),
                ('tos', models.DecimalField(decimal_places=1, max_digits=4)),
                ('missingOl', models.DecimalField(decimal_places=1, max_digits=4)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SatsScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('overall', models.DecimalField(decimal_places=1, max_digits=3)),
                ('driver', models.DecimalField(decimal_places=1, max_digits=3)),
                ('response', models.DecimalField(decimal_places=1, max_digits=3)),
                ('kmi', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
