# Generated by Django 2.2 on 2020-04-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satscores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversats',
            name='minIntow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driversats',
            name='paidCalls',
            field=models.IntegerField(default=0),
        ),
    ]
