# Generated by Django 2.2 on 2020-04-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satscores', '0002_auto_20200406_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driversats',
            name='missingOl',
            field=models.IntegerField(default=0),
        ),
    ]
