# Generated by Django 2.2 on 2020-04-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satscores', '0003_auto_20200406_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='satsscores',
            name='lostCalls',
            field=models.IntegerField(default=0),
        ),
    ]
