# Generated by Django 2.2 on 2020-04-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satscores', '0004_satsscores_lostcalls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driversats',
            name='missingOl',
        ),
        migrations.AddField(
            model_name='driversats',
            name='driversat',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='driversats',
            name='overallsat',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='driversats',
            name='name',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='driversats',
            name='rt60',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='driversats',
            name='tos',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
