# Generated by Django 2.2 on 2020-04-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satscores', '0005_auto_20200406_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driversats',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
