# Generated by Django 2.2 on 2020-04-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satscores', '0006_auto_20200406_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='satsscores',
            name='aaacalls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='satsscores',
            name='under60Min',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
